-- Feature tables
CREATE OR REPLACE TABLE SPARK_DB.SPARK_SCHEMA.DNS_FEATURES (
    TS_WINDOW_START VARCHAR,
    ID_ORIG_H VARCHAR,
    QUERY_RATE FLOAT,
    UNIQUE_QUERIES BIGINT,
    AVG_QUERY_LEN DOUBLE,
    QUERY_NAME_ENTROPY FLOAT,
    VM_ID VARCHAR
);

CREATE OR REPLACE TABLE SPARK_DB.SPARK_SCHEMA.NOTICE_FEATURES (
    TS_WINDOW_START VARCHAR,
    ID_ORIG_H VARCHAR,
    DNS_TUNNELING_NOTICES BIGINT,
    AVG_NOTICE_MSG_LEN DOUBLE,
    VM_ID VARCHAR
);

-- Baseline table
CREATE OR REPLACE TABLE SPARK_DB.SPARK_SCHEMA.DNS_BASELINE
CLUSTER BY (ID_ORIG_H) (
    ID_ORIG_H VARCHAR(16777216),
    METRIC VARCHAR(16777216),
    MEAN FLOAT,
    STD_DEV FLOAT,
    LAST_UPDATED TIMESTAMP_NTZ(9)
);

-- Anomalies table
CREATE OR REPLACE TABLE SPARK_DB.SPARK_SCHEMA.ANOMALIES
CLUSTER BY (YEAR(TIMESTAMP), MONTH(TIMESTAMP), DAY(TIMESTAMP)) (
    TIMESTAMP TIMESTAMP_NTZ(9),
    ID_ORIG_H VARCHAR(16777216),
    VM_ID VARCHAR(16777216),
    ANOMALY_TYPE VARCHAR(16777216),
    SCORE FLOAT,
    DETAILS VARCHAR(16777216)
);
