CREATE OR REPLACE TABLE ZEEK_SSL (
    YEAR INTEGER,
    MONTH INTEGER,
    DAY INTEGER,
    HOUR INTEGER,
    MINUTE INTEGER,
    SECOND INTEGER,
    TIMESTAMP TIMESTAMP_NTZ,
    UID STRING,
    ID_ORIG_H STRING,
    ID_ORIG_P INTEGER,
    ID_RESP_H STRING,
    ID_RESP_P INTEGER,
    VERSION STRING,
    CIPHER STRING,
    CURVE STRING,
    SERVER_NAME STRING,
    RESUMED BOOLEAN,
    ESTABLISHED BOOLEAN,
    SSL_HISTORY STRING,
    HOSTNAME STRING,
    VM_ID STRING
)
CLUSTER BY (YEAR, MONTH, DAY);