CREATE OR REPLACE TABLE ZEEK_CAPTURE_LOSS (
    YEAR INTEGER,
    MONTH INTEGER,
    DAY INTEGER,
    HOUR INTEGER,
    MINUTE INTEGER,
    SECOND INTEGER,
    TIMESTAMP TIMESTAMP_NTZ,
    TS_DELTA FLOAT,
    PEER STRING,
    GAPS INTEGER,
    ACKS INTEGER,
    PERCENT_LOST FLOAT,
    LOSS_SEVERITY STRING,
    HOSTNAME STRING,
    VM_ID STRING
)
CLUSTER BY (YEAR, MONTH, DAY);